import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// // app/layout.tsx ou app/page.tsx
// import { AuthProvider } from "@/AuthContext";

// export default function RootLayout({ children }) {
//   return (
//     <AuthProvider>
//       {children}
//     </AuthProvider>
//   );
// }
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "My Shopping List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
